/**
 * @file supabaseSql.ts
 * @description Supabase SQL Editor에서 바로 복사하여 실행할 수 있는 테이블 생성 및 데이터 삽입 SQL 스크립트
 */

// 1. cafe_menu 테이블 생성 SQL 쿼리문
export const CREATE_TABLE_SQL = `-- [바이브 카페] 주문 및 메뉴 관리 테이블 생성 쿼리문
-- Supabase 대시보드 -> SQL Editor에 붙여넣고 RUN 버튼을 눌러 실행하세요.

CREATE TABLE IF NOT EXISTS cafe_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 주문 고유 번호 (기본 키)
    customer_name VARCHAR(100) NOT NULL,                    -- 주문자 이름 (필수, text)
    phone_number VARCHAR(50),                               -- 전화번호 (tel)
    beverage_name VARCHAR(100) NOT NULL,                    -- 음료 이름 (아메리카노, 카페라떼 등)
    beverage_price INTEGER NOT NULL,                        -- 음료 기본 가격 (원)
    size VARCHAR(10) NOT NULL DEFAULT 'M',                  -- 음료 사이즈 ('S', 'M', 'L')
    size_price INTEGER NOT NULL DEFAULT 500,                -- 사이즈 추가 금액 (원)
    options TEXT[],                                         -- 추가 옵션 배열 (예: ARRAY['샷 추가', '크림 추가'])
    options_price INTEGER NOT NULL DEFAULT 0,               -- 추가 옵션 총액 (원)
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 1 AND quantity <= 10), -- 수량 (최소 1, 최대 10)
    total_price INTEGER NOT NULL,                           -- 최종 예상/결제 총 금액 (원)
    request_memo TEXT,                                      -- 고객 요청사항 (textarea)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()       -- 주문 접수 일시
);

-- 테이블 설명 코멘트 추가
COMMENT ON TABLE cafe_menu IS '바이브 카페 주문서 및 주문 내역 테이블';
COMMENT ON COLUMN cafe_menu.customer_name IS '주문 고객 이름';
COMMENT ON COLUMN cafe_menu.beverage_name IS '주문 음료 메뉴명';
COMMENT ON COLUMN cafe_menu.size IS '선택한 사이즈 (S, M, L)';
COMMENT ON COLUMN cafe_menu.options IS '선택한 추가 옵션 목록 (배열)';
COMMENT ON COLUMN cafe_menu.total_price IS '최종 결제 금액';

-- Supabase RLS (Row Level Security) 설정
ALTER TABLE cafe_menu ENABLE ROW LEVEL SECURITY;

-- 모든 사용자(익명/인증)가 주문을 등록(INSERT)할 수 있도록 허용
CREATE POLICY "누구나 주문 등록 가능" 
ON cafe_menu FOR INSERT 
TO public 
WITH CHECK (true);

-- 모든 사용자(익명/인증)가 주문 내역을 조회(SELECT)할 수 있도록 허용
CREATE POLICY "누구나 주문 내역 조회 가능" 
ON cafe_menu FOR SELECT 
TO public 
USING (true);
`;

// 2. 테스트용 1건 가짜 데이터 INSERT 쿼리문
export const INSERT_DUMMY_DATA_SQL = `-- [바이브 카페] 테스트용 1건 가짜 데이터 INSERT 쿼리문
-- '홍길동' 고객의 카페라떼 M사이즈(샷 추가) 주문 예시

INSERT INTO cafe_menu (
    customer_name,
    phone_number,
    beverage_name,
    beverage_price,
    size,
    size_price,
    options,
    options_price,
    quantity,
    total_price,
    request_memo
) VALUES (
    '홍길동',
    '010-1234-5678',
    '카페라떼',
    4000,
    'M',
    500,
    ARRAY['샷 추가'],
    500,
    1,
    5000,
    '얼음 적게 넣어주시고 시원하게 부탁드립니다!'
);
`;

/**
 * 접수된 실제 주문 객체를 Supabase INSERT SQL 문자열로 변환하는 유틸리티 함수
 */
export function generateOrderInsertSql(order: {
  customerName: string;
  phoneNumber: string;
  beverageName: string;
  beveragePrice: number;
  size: string;
  sizePrice: number;
  selectedOptionsText: string[];
  extraOptionsPrice: number;
  quantity: number;
  totalPrice: number;
  requestMemo: string;
}): string {
  const optionsArrayString = order.selectedOptionsText.length > 0
    ? `ARRAY[${order.selectedOptionsText.map(opt => `'${opt}'`).join(', ')}]`
    : `ARRAY[]::TEXT[]`;

  return `INSERT INTO cafe_menu (
    customer_name,
    phone_number,
    beverage_name,
    beverage_price,
    size,
    size_price,
    options,
    options_price,
    quantity,
    total_price,
    request_memo
) VALUES (
    '${order.customerName.replace(/'/g, "''")}',
    '${order.phoneNumber.replace(/'/g, "''")}',
    '${order.beverageName.replace(/'/g, "''")}',
    ${order.beveragePrice},
    '${order.size}',
    ${order.sizePrice},
    ${optionsArrayString},
    ${order.extraOptionsPrice},
    ${order.quantity},
    ${order.totalPrice},
    ${order.requestMemo ? `'${order.requestMemo.replace(/'/g, "''")}'` : 'NULL'}
);`;
}
